name: Python application test with Github Actions

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
          PYTHONPATH: ${{ github.workspace }}/starter
    - name: Run pytest
      run: |
        pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/starter
    - name: Run flake8
      run: |
        pip install flake8
        flake8 .
      env:
        PYTHONPATH: ${{ github.workspace }}/starter